### ISSUE TITLE
Claim 1:  The 64,000 um3 box imaged at high resolution had roughly 13.7 million cell profiles in its 1850 sections.

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#13]
Do Something:
- [ ] Download volume at scale 3
- [ ] Do connected components on each slice
- [ ] Sum unique labels per slice

Potential Improvements:
- [ ] Ensure that branched objects with the same label are counted twice
- [ ] Resolve which masking to use for this claim
- [ ] Use only dense cylinder and extrapolate to full volume
- [ ] Correct for relabeling cell parts (e.g., spines to dendrites)
- [ ] Try to understand discrepancy with paper number

**Comment by jovo** [comment]
we get different answers than they say we should.
can we explain the discrepancy discrepancy?
shall we ask bobby?

**Comment by wrgr** [comment]
Sure!  We need a good strategy (batch?) to make this less overwhelming, perhaps.

**Comment by jovo** [comment]
sure, let's ask when we are done.

**Comment by jovo** [comment]
in any case, i vote we close this issue, and maybe make a new issue with all claim 1 outstanding thoughts (or 1 for all claims?)

**Comment by wrgr** [comment]
obe
