### ISSUE TITLE
Claim 5:  There were 1,700 synapses at a density of one synapse per 1.13 μm3.

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#18]
Do Something:
- [ ] Download all synapse metadata
- [ ] Count total number of pixels in masked volume
- [ ] Convert pixels to microns
- [ ] Report total number of synapses and synapses per volume

Potential Improvements:
- [ ] Resolve orphan synapses
- [ ] Determine relevant volume

**Comment by jovo** [comment]
this one seems done?
if so, let's close this issue?
maybe we need an "improve claims" issue?

**Comment by wrgr** [comment]
obe
