### ISSUE TITLE
Read Bobby Paper

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#2]
Summarize in some way meaningful to you.

**Comment by j6k4m8** [comment]
...should I close..?

**Comment by wrgr** [comment]
If you did it!  :)

Output of that task is a sense of what to expect from the data and the sort
of organization you might want.  You'll have questions, like explain ramon
types to me...make a list and we'll answer them on Tuesday.

Best,
Will

**Comment by wrgr** [comment]
making progress!

Best,
Will
