### ISSUE TITLE
Claim 7:  The non-cellular (extracellular) space accounts for 6% of the total volume, less than half the extracellular space estimates from living brains.

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#23]
Do Something:
- [ ] Download mask volume and count voxels
- [ ] Count volume of all objects in mask slices
- [ ] Compute percentage of extracellular space

Potential Improvements:
- [ ] Restrict to cylinders with extracellular space (automatic cylinder may not have any!)

**Comment by jovo** [comment]
this is done?

**Comment by wrgr** [comment]
obe - refactoring
