### ISSUE TITLE
for claims in general

### ISSUE THREAD

**Issue by jovo** [neurodata/kasthuri2015#27]
- [ ] make sure to include their actual claim somewhere
- [ ] including timing for each is great, when possible, include the start and stop times in a single cell.

@willgray @j6k4m8

**Comment by wrgr** [comment]
How about ~

First cell:  Claim (Capability) (e.g., count the number of vesicles in cylinder 1)
2 - (n-1):  Work
Last cell (needs to be last bc depends on notebook results):

Our result:  _____
Kasthuri 2015 result:  ______
(optional editorial explanation when appropriate for broader community)
Timing for notebook:  XX minutes 
ndio version used:  vX.X

Seems like a nice standard?

**Comment by jovo** [comment]
i like the absolute last thing being a number that is our answer.

@j6k4m8 had a spec in mind earlier that was more detailed?

On Mon, Feb 15, 2016 at 1:19 PM, William Gray notifications@github.com
wrote:

> How about ~
> 
> First cell: Claim (Capability) (e.g., count the number of vesicles in
> cylinder 1)
> 2 - (n-1): Work
> Last cell (needs to be last bc depends on notebook results):
> 
> Our result: _____
> Kasthuri 2015 result: ______
> (optional editorial explanation when appropriate for broader community)
> Timing for notebook: XX minutes
> ndio version used: vX.X
> 
> Seems like a nice standard?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/kasthuri2015/issues/27#issuecomment-184334572
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
resolved in refactoring.
