### ISSUE TITLE
Access to saturated annotations

### ISSUE THREAD

**Issue by mattroos** [neurodata/kasthuri2015#28]
Can we get saturated annotations at user-specified resolution?

**Comment by jovo** [comment]
hi @mattroos :-)
you can, @willgray @j6k4m8 can point you to python code.
which dataset are you wanting?
we have:
AC3
AC4
various kasthruri thingies
and another dataset from kristen harris (in hippocampus), which is particularly beautiful..

**Comment by mattroos** [comment]
Thanks @jovo! Looking for multi-cylinder volume a la Figure 3E in the 2015 paper.  Just got done talking to @willgray about it.  Harris data sounds cool.  Maybe be smaller than I want but will keep it mind.

**Comment by jovo** [comment]
cool, so, issue closed?

**Comment by wrgr** [comment]
issue open until we deliver it.  :)

**Comment by wrgr** [comment]
Here is a link to the download script:  https://github.com/neurodata/kasthuri2015/blob/master/claims/claim0_get_data.ipynb

**Comment by mattroos** [comment]
Thanks, @willgray!
