### ISSUE TITLE
add touch matrix

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#30]
This was harder than expected.  Currently have added functionality to better parse metadata so that we have a good way to isolate spines and their shafts, and made progress toward the below items.  

Roadmap (completion beginning of next week):
- Efficiently parse segment metadata (done)
- Isolate spines (done)
- Rewrite segment paint to common neuron paint
- Build a matrix in a way compatible with the cell paper [3xN?]
- dilate spines (1 by 1?  All at once?) and form matrix

@jovo - comments/feedback welcome.  My top ND issue for the week.

**Comment by jovo** [comment]
great! thanks for info.
maybe comment in "weekly-status-reports" so there is a consistent place to
keep track of such things?

On Tue, Apr 5, 2016 at 9:33 AM, William Gray notifications@github.com
wrote:

> This was harder than expected. Currently have added functionality to
> better parse metadata so that we have a good way to isolate spines and
> their shafts, and made progress toward the below items.
> 
> Roadmap (completion beginning of next week):
> - Efficiently parse segment metadata (done)
> - Isolate spines (done)
> - Rewrite segment paint to common neuron paint
> - Build a matrix in a way compatible with the cell paper [3xN?]
> - dilate spines (1 by 1? All at once?) and form matrix
> 
> @jovo https://github.com/jovo - comments/feedback welcome. My top ND
> issue for the week.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/kasthuri2015/issues/30

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
In re-reading the supplement, seems that the input is slightly different than I thought:

"The inputs to the Monte Carlo procedure are one matrix containing the number of times each axon touches each dendritic spine (usually 0 or 1) and a second, corresponding matrix that contains the number of synapses each axon forms with each spine (usually 0 or 1)."

So I'm going to make the matrices in this way.  This means the matrix is ~1295x600 or so...and that both matrices are different from the overall graph.  It's easiest to make this first, so will do so and then we can iterate.

**Comment by jovo** [comment]
ok, good catch, note that will make the statistics impossible.

**Comment by wrgr** [comment]
i thought you might say that.  we can simplify (contract?) the resulting graph by choosing to then use neuron labels vs. spine labels, perhaps restricting to high degree.  Don't know what the dimensions of that matrix will be or if it's amenable to analysis, but trivial to make from the other one.  And much smaller, at least in one dimension.

**Comment by jovo** [comment]
don't worry about it yet, let's just get the data right.

On Sun, Apr 10, 2016 at 9:07 AM, William Gray notifications@github.com
wrote:

> i thought you might say that. we can simplify (contract?) the resulting
> graph by choosing to then use neuron labels vs. spine labels, perhaps
> restricting to high degree. Don't know what the dimensions of that matrix
> will be or if it's amenable to analysis, but trivial to make from the other
> one. And much smaller, at least in one dimension.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/kasthuri2015/issues/30#issuecomment-207982857

## 

the glass is all full:  half water, half air.
neurodata.io
