### ISSUE TITLE
Kasthuri Claims v0.15

### ISSUE THREAD

**Issue by wrgr** [neurodata/kasthuri2015#9]
Due on THURSDAY, 9/24 (when Will's back)
- Enumerate larger list of Kasthuri claims, to include counting and data characterization type actions
- Characterize each claim as easy, medium, hard, and whether we plan to accomplish via CAJAL or OCPY
- To facilitate ndio python notebooks and reproducible kasthuri science, complete baseline of ndio by wrapping all RESTful calls in a ndio.Remote (so, ndio.OCPRemote.get_cutout( . . . ), ndio.OCPRemote.get_all_of_type( . . . ) etc) - this completes core functionality and also identifies any gaps in restful call documentation
- Submit a git issue to openconnectome repo with any documentation that is unclear
- Run at least 5 new Kasthuri claims

@jovo

**Comment by wrgr** [comment]
@j6k4m8

**Comment by jovo** [comment]
@j6k4m8 status update on this please?
